# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Harris Osserman
tagline:          ''
description:      '👋 I’m the Founder & CEO at Talk Hiring. We’re building a realistic mock interviewing tool with instant feedback that’s fully automated.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
